server:
  port: 8001

spring:
  redis:
    database: 0
    host: 192.168.1.201
    port: 6379
    password: 123456

# 在dev环境开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


